version: 3
endpoint: http://localhost:3002
metadata_directory: hasura/metadata
migrations_directory: hasura/migrations
seeds_directory: hasura/seeds
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
