version: '3.6'
services:
  client:
    build:
      context: client/.
      dockerfile: Dockerfile-dev
    depends_on:
      - api
    env_file:
      - client/.env.local
    volumes:
      - ./client/.:/opt/client
      - /opt/client/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    image: "cr_client:latest"
  
  api:
    build:
      context: api/.
      dockerfile: Dockerfile-dev
    depends_on:
      - hasura
    env_file:
      - api/.env
    volumes:
      - ./api/.:/opt/api
      - /opt/api/node_modules
    ports:
      - '3006:3006'
      - '3008:3008'
      - '9229:9229'
    image: "cr_api:latest"
    restart: always

  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
        - "6543:5432"
    environment:
      - POSTGRES_DB=value
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgpass

  hasura:
    image: hasura/graphql-engine:v2.3.1
    ports:
      - "${HASURA_GRAPHQL_SERVER_PORT}:${HASURA_GRAPHQL_SERVER_PORT}"
    depends_on:
      - "postgres"
    restart: always
    env_file:
      - .env
    command:
      - graphql-engine
      - serve
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  db_data:
