org: lkuich
app: creative-repo-storage
service: creative-repo-storage
frameworkVersion: '3'
custom: ${file(./env.yml)}

provider:
  name: aws
  runtime: nodejs14.x
  apiGateway:
    binaryMediaTypes:
      - '*/*'
  environment:
    S3_BUCKET: ${self:custom.S3_BUCKET}
    S3_ACCESS_KEY_ID: ${self:custom.S3_ACCESS_KEY_ID}
    S3_SECRET_ACCESS_KEY: ${self:custom.S3_SECRET_ACCESS_KEY}
    AUTH0_AUD: ${self:custom.AUTH0_AUD}
    AUTH0_URI: ${self:custom.AUTH0_URI}
    DATABASE_URL: ${self:custom.DATABASE_URL}
    HASURA_GRAPHQL_ADMIN_SECRET: ${self:custom.HASURA_GRAPHQL_ADMIN_SECRET}

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'
